// <copyright file="CodeEnum.cs" company="APIMatic">
// GeoDBCitiesAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using APIMatic.Core.Utilities.Converters;
using GeoDBCitiesAPI.Standard;
using GeoDBCitiesAPI.Standard.Utilities;
using Newtonsoft.Json;

namespace GeoDBCitiesAPI.Standard.Models
{
    /// <summary>
    /// CodeEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CodeEnum
    {
        /// <summary>
        /// Undefined.
        /// </summary>
        [EnumMember(Value = "undefined")]
        Undefined,

        /// <summary>
        /// Aa.
        /// </summary>
        [EnumMember(Value = "aa")]
        Aa,

        /// <summary>
        /// Ab.
        /// </summary>
        [EnumMember(Value = "ab")]
        Ab,

        /// <summary>
        /// Ae.
        /// </summary>
        [EnumMember(Value = "ae")]
        Ae,

        /// <summary>
        /// Af.
        /// </summary>
        [EnumMember(Value = "af")]
        Af,

        /// <summary>
        /// Ak.
        /// </summary>
        [EnumMember(Value = "ak")]
        Ak,

        /// <summary>
        /// Am.
        /// </summary>
        [EnumMember(Value = "am")]
        Am,

        /// <summary>
        /// An.
        /// </summary>
        [EnumMember(Value = "an")]
        An,

        /// <summary>
        /// Ar.
        /// </summary>
        [EnumMember(Value = "ar")]
        Ar,

        /// <summary>
        /// As.
        /// </summary>
        [EnumMember(Value = "as")]
        As,

        /// <summary>
        /// Av.
        /// </summary>
        [EnumMember(Value = "av")]
        Av,

        /// <summary>
        /// Ay.
        /// </summary>
        [EnumMember(Value = "ay")]
        Ay,

        /// <summary>
        /// Az.
        /// </summary>
        [EnumMember(Value = "az")]
        Az,

        /// <summary>
        /// Ba.
        /// </summary>
        [EnumMember(Value = "ba")]
        Ba,

        /// <summary>
        /// Be.
        /// </summary>
        [EnumMember(Value = "be")]
        Be,

        /// <summary>
        /// Bg.
        /// </summary>
        [EnumMember(Value = "bg")]
        Bg,

        /// <summary>
        /// Bh.
        /// </summary>
        [EnumMember(Value = "bh")]
        Bh,

        /// <summary>
        /// Bi.
        /// </summary>
        [EnumMember(Value = "bi")]
        Bi,

        /// <summary>
        /// Bm.
        /// </summary>
        [EnumMember(Value = "bm")]
        Bm,

        /// <summary>
        /// Bn.
        /// </summary>
        [EnumMember(Value = "bn")]
        Bn,

        /// <summary>
        /// Bo.
        /// </summary>
        [EnumMember(Value = "bo")]
        Bo,

        /// <summary>
        /// Br.
        /// </summary>
        [EnumMember(Value = "br")]
        Br,

        /// <summary>
        /// Bs.
        /// </summary>
        [EnumMember(Value = "bs")]
        Bs,

        /// <summary>
        /// Ca.
        /// </summary>
        [EnumMember(Value = "ca")]
        Ca,

        /// <summary>
        /// Ce.
        /// </summary>
        [EnumMember(Value = "ce")]
        Ce,

        /// <summary>
        /// Ch.
        /// </summary>
        [EnumMember(Value = "ch")]
        Ch,

        /// <summary>
        /// Co.
        /// </summary>
        [EnumMember(Value = "co")]
        Co,

        /// <summary>
        /// Cr.
        /// </summary>
        [EnumMember(Value = "cr")]
        Cr,

        /// <summary>
        /// Cs.
        /// </summary>
        [EnumMember(Value = "cs")]
        Cs,

        /// <summary>
        /// Cu.
        /// </summary>
        [EnumMember(Value = "cu")]
        Cu,

        /// <summary>
        /// Cv.
        /// </summary>
        [EnumMember(Value = "cv")]
        Cv,

        /// <summary>
        /// Cy.
        /// </summary>
        [EnumMember(Value = "cy")]
        Cy,

        /// <summary>
        /// Da.
        /// </summary>
        [EnumMember(Value = "da")]
        Da,

        /// <summary>
        /// De.
        /// </summary>
        [EnumMember(Value = "de")]
        De,

        /// <summary>
        /// Dv.
        /// </summary>
        [EnumMember(Value = "dv")]
        Dv,

        /// <summary>
        /// Dz.
        /// </summary>
        [EnumMember(Value = "dz")]
        Dz,

        /// <summary>
        /// Ee.
        /// </summary>
        [EnumMember(Value = "ee")]
        Ee,

        /// <summary>
        /// El.
        /// </summary>
        [EnumMember(Value = "el")]
        El,

        /// <summary>
        /// En.
        /// </summary>
        [EnumMember(Value = "en")]
        En,

        /// <summary>
        /// Eo.
        /// </summary>
        [EnumMember(Value = "eo")]
        Eo,

        /// <summary>
        /// Es.
        /// </summary>
        [EnumMember(Value = "es")]
        Es,

        /// <summary>
        /// Et.
        /// </summary>
        [EnumMember(Value = "et")]
        Et,

        /// <summary>
        /// Eu.
        /// </summary>
        [EnumMember(Value = "eu")]
        Eu,

        /// <summary>
        /// Fa.
        /// </summary>
        [EnumMember(Value = "fa")]
        Fa,

        /// <summary>
        /// Ff.
        /// </summary>
        [EnumMember(Value = "ff")]
        Ff,

        /// <summary>
        /// Fi.
        /// </summary>
        [EnumMember(Value = "fi")]
        Fi,

        /// <summary>
        /// Fj.
        /// </summary>
        [EnumMember(Value = "fj")]
        Fj,

        /// <summary>
        /// Fo.
        /// </summary>
        [EnumMember(Value = "fo")]
        Fo,

        /// <summary>
        /// Fr.
        /// </summary>
        [EnumMember(Value = "fr")]
        Fr,

        /// <summary>
        /// Fy.
        /// </summary>
        [EnumMember(Value = "fy")]
        Fy,

        /// <summary>
        /// Ga.
        /// </summary>
        [EnumMember(Value = "ga")]
        Ga,

        /// <summary>
        /// Gd.
        /// </summary>
        [EnumMember(Value = "gd")]
        Gd,

        /// <summary>
        /// Gl.
        /// </summary>
        [EnumMember(Value = "gl")]
        Gl,

        /// <summary>
        /// Gn.
        /// </summary>
        [EnumMember(Value = "gn")]
        Gn,

        /// <summary>
        /// Gu.
        /// </summary>
        [EnumMember(Value = "gu")]
        Gu,

        /// <summary>
        /// Gv.
        /// </summary>
        [EnumMember(Value = "gv")]
        Gv,

        /// <summary>
        /// Ha.
        /// </summary>
        [EnumMember(Value = "ha")]
        Ha,

        /// <summary>
        /// He.
        /// </summary>
        [EnumMember(Value = "he")]
        He,

        /// <summary>
        /// Hi.
        /// </summary>
        [EnumMember(Value = "hi")]
        Hi,

        /// <summary>
        /// Ho.
        /// </summary>
        [EnumMember(Value = "ho")]
        Ho,

        /// <summary>
        /// Hr.
        /// </summary>
        [EnumMember(Value = "hr")]
        Hr,

        /// <summary>
        /// Ht.
        /// </summary>
        [EnumMember(Value = "ht")]
        Ht,

        /// <summary>
        /// Hu.
        /// </summary>
        [EnumMember(Value = "hu")]
        Hu,

        /// <summary>
        /// Hy.
        /// </summary>
        [EnumMember(Value = "hy")]
        Hy,

        /// <summary>
        /// Hz.
        /// </summary>
        [EnumMember(Value = "hz")]
        Hz,

        /// <summary>
        /// Ia.
        /// </summary>
        [EnumMember(Value = "ia")]
        Ia,

        /// <summary>
        /// Id.
        /// </summary>
        [EnumMember(Value = "id")]
        Id,

        /// <summary>
        /// Ie.
        /// </summary>
        [EnumMember(Value = "ie")]
        Ie,

        /// <summary>
        /// Ig.
        /// </summary>
        [EnumMember(Value = "ig")]
        Ig,

        /// <summary>
        /// Ii.
        /// </summary>
        [EnumMember(Value = "ii")]
        Ii,

        /// <summary>
        /// Ik.
        /// </summary>
        [EnumMember(Value = "ik")]
        Ik,

        /// <summary>
        /// Io.
        /// </summary>
        [EnumMember(Value = "io")]
        Io,

        /// <summary>
        /// Is.
        /// </summary>
        [EnumMember(Value = "is")]
        Is,

        /// <summary>
        /// It.
        /// </summary>
        [EnumMember(Value = "it")]
        It,

        /// <summary>
        /// Iu.
        /// </summary>
        [EnumMember(Value = "iu")]
        Iu,

        /// <summary>
        /// Ja.
        /// </summary>
        [EnumMember(Value = "ja")]
        Ja,

        /// <summary>
        /// Jv.
        /// </summary>
        [EnumMember(Value = "jv")]
        Jv,

        /// <summary>
        /// Ka.
        /// </summary>
        [EnumMember(Value = "ka")]
        Ka,

        /// <summary>
        /// Kg.
        /// </summary>
        [EnumMember(Value = "kg")]
        Kg,

        /// <summary>
        /// Ki.
        /// </summary>
        [EnumMember(Value = "ki")]
        Ki,

        /// <summary>
        /// Kj.
        /// </summary>
        [EnumMember(Value = "kj")]
        Kj,

        /// <summary>
        /// Kk.
        /// </summary>
        [EnumMember(Value = "kk")]
        Kk,

        /// <summary>
        /// Kl.
        /// </summary>
        [EnumMember(Value = "kl")]
        Kl,

        /// <summary>
        /// Km.
        /// </summary>
        [EnumMember(Value = "km")]
        Km,

        /// <summary>
        /// Kn.
        /// </summary>
        [EnumMember(Value = "kn")]
        Kn,

        /// <summary>
        /// Ko.
        /// </summary>
        [EnumMember(Value = "ko")]
        Ko,

        /// <summary>
        /// Kr.
        /// </summary>
        [EnumMember(Value = "kr")]
        Kr,

        /// <summary>
        /// Ks.
        /// </summary>
        [EnumMember(Value = "ks")]
        Ks,

        /// <summary>
        /// Ku.
        /// </summary>
        [EnumMember(Value = "ku")]
        Ku,

        /// <summary>
        /// Kv.
        /// </summary>
        [EnumMember(Value = "kv")]
        Kv,

        /// <summary>
        /// Kw.
        /// </summary>
        [EnumMember(Value = "kw")]
        Kw,

        /// <summary>
        /// Ky.
        /// </summary>
        [EnumMember(Value = "ky")]
        Ky,

        /// <summary>
        /// La.
        /// </summary>
        [EnumMember(Value = "la")]
        La,

        /// <summary>
        /// Lb.
        /// </summary>
        [EnumMember(Value = "lb")]
        Lb,

        /// <summary>
        /// Lg.
        /// </summary>
        [EnumMember(Value = "lg")]
        Lg,

        /// <summary>
        /// Li.
        /// </summary>
        [EnumMember(Value = "li")]
        Li,

        /// <summary>
        /// Ln.
        /// </summary>
        [EnumMember(Value = "ln")]
        Ln,

        /// <summary>
        /// Lo.
        /// </summary>
        [EnumMember(Value = "lo")]
        Lo,

        /// <summary>
        /// Lt.
        /// </summary>
        [EnumMember(Value = "lt")]
        Lt,

        /// <summary>
        /// Lu.
        /// </summary>
        [EnumMember(Value = "lu")]
        Lu,

        /// <summary>
        /// Lv.
        /// </summary>
        [EnumMember(Value = "lv")]
        Lv,

        /// <summary>
        /// Mg.
        /// </summary>
        [EnumMember(Value = "mg")]
        Mg,

        /// <summary>
        /// Mh.
        /// </summary>
        [EnumMember(Value = "mh")]
        Mh,

        /// <summary>
        /// Mi.
        /// </summary>
        [EnumMember(Value = "mi")]
        Mi,

        /// <summary>
        /// Mk.
        /// </summary>
        [EnumMember(Value = "mk")]
        Mk,

        /// <summary>
        /// Ml.
        /// </summary>
        [EnumMember(Value = "ml")]
        Ml,

        /// <summary>
        /// Mn.
        /// </summary>
        [EnumMember(Value = "mn")]
        Mn,

        /// <summary>
        /// Mr.
        /// </summary>
        [EnumMember(Value = "mr")]
        Mr,

        /// <summary>
        /// Ms.
        /// </summary>
        [EnumMember(Value = "ms")]
        Ms,

        /// <summary>
        /// Mt.
        /// </summary>
        [EnumMember(Value = "mt")]
        Mt,

        /// <summary>
        /// My.
        /// </summary>
        [EnumMember(Value = "my")]
        My,

        /// <summary>
        /// Na.
        /// </summary>
        [EnumMember(Value = "na")]
        Na,

        /// <summary>
        /// Nb.
        /// </summary>
        [EnumMember(Value = "nb")]
        Nb,

        /// <summary>
        /// Nd.
        /// </summary>
        [EnumMember(Value = "nd")]
        Nd,

        /// <summary>
        /// Ne.
        /// </summary>
        [EnumMember(Value = "ne")]
        Ne,

        /// <summary>
        /// Ng.
        /// </summary>
        [EnumMember(Value = "ng")]
        Ng,

        /// <summary>
        /// Nl.
        /// </summary>
        [EnumMember(Value = "nl")]
        Nl,

        /// <summary>
        /// Nn.
        /// </summary>
        [EnumMember(Value = "nn")]
        Nn,

        /// <summary>
        /// No.
        /// </summary>
        [EnumMember(Value = "no")]
        No,

        /// <summary>
        /// Nr.
        /// </summary>
        [EnumMember(Value = "nr")]
        Nr,

        /// <summary>
        /// Nv.
        /// </summary>
        [EnumMember(Value = "nv")]
        Nv,

        /// <summary>
        /// Ny.
        /// </summary>
        [EnumMember(Value = "ny")]
        Ny,

        /// <summary>
        /// Oc.
        /// </summary>
        [EnumMember(Value = "oc")]
        Oc,

        /// <summary>
        /// Oj.
        /// </summary>
        [EnumMember(Value = "oj")]
        Oj,

        /// <summary>
        /// Om.
        /// </summary>
        [EnumMember(Value = "om")]
        Om,

        /// <summary>
        /// Or.
        /// </summary>
        [EnumMember(Value = "or")]
        Or,

        /// <summary>
        /// Os.
        /// </summary>
        [EnumMember(Value = "os")]
        Os,

        /// <summary>
        /// Pa.
        /// </summary>
        [EnumMember(Value = "pa")]
        Pa,

        /// <summary>
        /// Pi.
        /// </summary>
        [EnumMember(Value = "pi")]
        Pi,

        /// <summary>
        /// Pl.
        /// </summary>
        [EnumMember(Value = "pl")]
        Pl,

        /// <summary>
        /// Ps.
        /// </summary>
        [EnumMember(Value = "ps")]
        Ps,

        /// <summary>
        /// Pt.
        /// </summary>
        [EnumMember(Value = "pt")]
        Pt,

        /// <summary>
        /// Qu.
        /// </summary>
        [EnumMember(Value = "qu")]
        Qu,

        /// <summary>
        /// Rm.
        /// </summary>
        [EnumMember(Value = "rm")]
        Rm,

        /// <summary>
        /// Rn.
        /// </summary>
        [EnumMember(Value = "rn")]
        Rn,

        /// <summary>
        /// Ro.
        /// </summary>
        [EnumMember(Value = "ro")]
        Ro,

        /// <summary>
        /// Ru.
        /// </summary>
        [EnumMember(Value = "ru")]
        Ru,

        /// <summary>
        /// Rw.
        /// </summary>
        [EnumMember(Value = "rw")]
        Rw,

        /// <summary>
        /// Sa.
        /// </summary>
        [EnumMember(Value = "sa")]
        Sa,

        /// <summary>
        /// Sc.
        /// </summary>
        [EnumMember(Value = "sc")]
        Sc,

        /// <summary>
        /// Sd.
        /// </summary>
        [EnumMember(Value = "sd")]
        Sd,

        /// <summary>
        /// Se.
        /// </summary>
        [EnumMember(Value = "se")]
        Se,

        /// <summary>
        /// Sg.
        /// </summary>
        [EnumMember(Value = "sg")]
        Sg,

        /// <summary>
        /// Si.
        /// </summary>
        [EnumMember(Value = "si")]
        Si,

        /// <summary>
        /// Sk.
        /// </summary>
        [EnumMember(Value = "sk")]
        Sk,

        /// <summary>
        /// Sl.
        /// </summary>
        [EnumMember(Value = "sl")]
        Sl,

        /// <summary>
        /// Sm.
        /// </summary>
        [EnumMember(Value = "sm")]
        Sm,

        /// <summary>
        /// Sn.
        /// </summary>
        [EnumMember(Value = "sn")]
        Sn,

        /// <summary>
        /// So.
        /// </summary>
        [EnumMember(Value = "so")]
        So,

        /// <summary>
        /// Sq.
        /// </summary>
        [EnumMember(Value = "sq")]
        Sq,

        /// <summary>
        /// Sr.
        /// </summary>
        [EnumMember(Value = "sr")]
        Sr,

        /// <summary>
        /// Ss.
        /// </summary>
        [EnumMember(Value = "ss")]
        Ss,

        /// <summary>
        /// St.
        /// </summary>
        [EnumMember(Value = "st")]
        St,

        /// <summary>
        /// Su.
        /// </summary>
        [EnumMember(Value = "su")]
        Su,

        /// <summary>
        /// Sv.
        /// </summary>
        [EnumMember(Value = "sv")]
        Sv,

        /// <summary>
        /// Sw.
        /// </summary>
        [EnumMember(Value = "sw")]
        Sw,

        /// <summary>
        /// Ta.
        /// </summary>
        [EnumMember(Value = "ta")]
        Ta,

        /// <summary>
        /// Te.
        /// </summary>
        [EnumMember(Value = "te")]
        Te,

        /// <summary>
        /// Tg.
        /// </summary>
        [EnumMember(Value = "tg")]
        Tg,

        /// <summary>
        /// Th.
        /// </summary>
        [EnumMember(Value = "th")]
        Th,

        /// <summary>
        /// Ti.
        /// </summary>
        [EnumMember(Value = "ti")]
        Ti,

        /// <summary>
        /// Tk.
        /// </summary>
        [EnumMember(Value = "tk")]
        Tk,

        /// <summary>
        /// Tl.
        /// </summary>
        [EnumMember(Value = "tl")]
        Tl,

        /// <summary>
        /// Tn.
        /// </summary>
        [EnumMember(Value = "tn")]
        Tn,

        /// <summary>
        /// To.
        /// </summary>
        [EnumMember(Value = "to")]
        To,

        /// <summary>
        /// Tr.
        /// </summary>
        [EnumMember(Value = "tr")]
        Tr,

        /// <summary>
        /// Ts.
        /// </summary>
        [EnumMember(Value = "ts")]
        Ts,

        /// <summary>
        /// Tt.
        /// </summary>
        [EnumMember(Value = "tt")]
        Tt,

        /// <summary>
        /// Tw.
        /// </summary>
        [EnumMember(Value = "tw")]
        Tw,

        /// <summary>
        /// Ty.
        /// </summary>
        [EnumMember(Value = "ty")]
        Ty,

        /// <summary>
        /// Ug.
        /// </summary>
        [EnumMember(Value = "ug")]
        Ug,

        /// <summary>
        /// Uk.
        /// </summary>
        [EnumMember(Value = "uk")]
        Uk,

        /// <summary>
        /// Ur.
        /// </summary>
        [EnumMember(Value = "ur")]
        Ur,

        /// <summary>
        /// Uz.
        /// </summary>
        [EnumMember(Value = "uz")]
        Uz,

        /// <summary>
        /// Ve.
        /// </summary>
        [EnumMember(Value = "ve")]
        Ve,

        /// <summary>
        /// Vi.
        /// </summary>
        [EnumMember(Value = "vi")]
        Vi,

        /// <summary>
        /// Vo.
        /// </summary>
        [EnumMember(Value = "vo")]
        Vo,

        /// <summary>
        /// Wa.
        /// </summary>
        [EnumMember(Value = "wa")]
        Wa,

        /// <summary>
        /// Wo.
        /// </summary>
        [EnumMember(Value = "wo")]
        Wo,

        /// <summary>
        /// Xh.
        /// </summary>
        [EnumMember(Value = "xh")]
        Xh,

        /// <summary>
        /// Yi.
        /// </summary>
        [EnumMember(Value = "yi")]
        Yi,

        /// <summary>
        /// Yo.
        /// </summary>
        [EnumMember(Value = "yo")]
        Yo,

        /// <summary>
        /// Za.
        /// </summary>
        [EnumMember(Value = "za")]
        Za,

        /// <summary>
        /// Zh.
        /// </summary>
        [EnumMember(Value = "zh")]
        Zh,

        /// <summary>
        /// Zu.
        /// </summary>
        [EnumMember(Value = "zu")]
        Zu
    }
}