// <copyright file="CountryRegionSummary.cs" company="APIMatic">
// GeoDBCitiesAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using GeoDBCitiesAPI.Standard;
using GeoDBCitiesAPI.Standard.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace GeoDBCitiesAPI.Standard.Models
{
    /// <summary>
    /// CountryRegionSummary.
    /// </summary>
    public class CountryRegionSummary
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CountryRegionSummary"/> class.
        /// </summary>
        public CountryRegionSummary()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CountryRegionSummary"/> class.
        /// </summary>
        /// <param name="countryCode">countryCode.</param>
        /// <param name="fipsCode">fipsCode.</param>
        /// <param name="isoCode">isoCode.</param>
        /// <param name="name">name.</param>
        /// <param name="wikiDataId">wikiDataId.</param>
        public CountryRegionSummary(
            string countryCode = null,
            string fipsCode = null,
            string isoCode = null,
            string name = null,
            string wikiDataId = null)
        {
            this.CountryCode = countryCode;
            this.FipsCode = fipsCode;
            this.IsoCode = isoCode;
            this.Name = name;
            this.WikiDataId = wikiDataId;
        }

        /// <summary>
        /// An ISO-3166 country code
        /// </summary>
        [JsonProperty("countryCode", NullValueHandling = NullValueHandling.Ignore)]
        public string CountryCode { get; set; }

        /// <summary>
        /// The FIPS 10-4 region code
        /// </summary>
        [JsonProperty("fipsCode", NullValueHandling = NullValueHandling.Ignore)]
        public string FipsCode { get; set; }

        /// <summary>
        /// The ISO region code
        /// </summary>
        [JsonProperty("isoCode", NullValueHandling = NullValueHandling.Ignore)]
        public string IsoCode { get; set; }

        /// <summary>
        /// The region name (varies by languageCode)
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <summary>
        /// The region WikiData id
        /// </summary>
        [JsonProperty("wikiDataId", NullValueHandling = NullValueHandling.Ignore)]
        public string WikiDataId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CountryRegionSummary : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CountryRegionSummary other &&
                (this.CountryCode == null && other.CountryCode == null ||
                 this.CountryCode?.Equals(other.CountryCode) == true) &&
                (this.FipsCode == null && other.FipsCode == null ||
                 this.FipsCode?.Equals(other.FipsCode) == true) &&
                (this.IsoCode == null && other.IsoCode == null ||
                 this.IsoCode?.Equals(other.IsoCode) == true) &&
                (this.Name == null && other.Name == null ||
                 this.Name?.Equals(other.Name) == true) &&
                (this.WikiDataId == null && other.WikiDataId == null ||
                 this.WikiDataId?.Equals(other.WikiDataId) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CountryCode = {this.CountryCode ?? "null"}");
            toStringOutput.Add($"FipsCode = {this.FipsCode ?? "null"}");
            toStringOutput.Add($"IsoCode = {this.IsoCode ?? "null"}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"WikiDataId = {this.WikiDataId ?? "null"}");
        }
    }
}