// <copyright file="CountryDetails.cs" company="APIMatic">
// GeoDBCitiesAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using GeoDBCitiesAPI.Standard;
using GeoDBCitiesAPI.Standard.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace GeoDBCitiesAPI.Standard.Models
{
    /// <summary>
    /// CountryDetails.
    /// </summary>
    public class CountryDetails
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CountryDetails"/> class.
        /// </summary>
        public CountryDetails()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CountryDetails"/> class.
        /// </summary>
        /// <param name="callingCode">callingCode.</param>
        /// <param name="code">code.</param>
        /// <param name="currencyCodes">currencyCodes.</param>
        /// <param name="flagImageUri">flagImageUri.</param>
        /// <param name="name">name.</param>
        /// <param name="numRegions">numRegions.</param>
        /// <param name="wikiDataId">wikiDataId.</param>
        public CountryDetails(
            string callingCode = null,
            string code = null,
            List<string> currencyCodes = null,
            string flagImageUri = null,
            string name = null,
            int? numRegions = null,
            string wikiDataId = null)
        {
            this.CallingCode = callingCode;
            this.Code = code;
            this.CurrencyCodes = currencyCodes;
            this.FlagImageUri = flagImageUri;
            this.Name = name;
            this.NumRegions = numRegions;
            this.WikiDataId = wikiDataId;
        }

        /// <summary>
        /// The country dialing prefix
        /// </summary>
        [JsonProperty("callingCode", NullValueHandling = NullValueHandling.Ignore)]
        public string CallingCode { get; set; }

        /// <summary>
        /// The ISO-3166 country code
        /// </summary>
        [JsonProperty("code", NullValueHandling = NullValueHandling.Ignore)]
        public string Code { get; set; }

        /// <summary>
        /// A list of supported ISO-4217 currency codes
        /// </summary>
        [JsonProperty("currencyCodes", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> CurrencyCodes { get; set; }

        /// <summary>
        /// The country flag image
        /// </summary>
        [JsonProperty("flagImageUri", NullValueHandling = NullValueHandling.Ignore)]
        public string FlagImageUri { get; set; }

        /// <summary>
        /// The country name (varies by languageCode)
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <summary>
        /// The number of regions in this country
        /// </summary>
        [JsonProperty("numRegions", NullValueHandling = NullValueHandling.Ignore)]
        public int? NumRegions { get; set; }

        /// <summary>
        /// The country WikiData id
        /// </summary>
        [JsonProperty("wikiDataId", NullValueHandling = NullValueHandling.Ignore)]
        public string WikiDataId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CountryDetails : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CountryDetails other &&
                (this.CallingCode == null && other.CallingCode == null ||
                 this.CallingCode?.Equals(other.CallingCode) == true) &&
                (this.Code == null && other.Code == null ||
                 this.Code?.Equals(other.Code) == true) &&
                (this.CurrencyCodes == null && other.CurrencyCodes == null ||
                 this.CurrencyCodes?.Equals(other.CurrencyCodes) == true) &&
                (this.FlagImageUri == null && other.FlagImageUri == null ||
                 this.FlagImageUri?.Equals(other.FlagImageUri) == true) &&
                (this.Name == null && other.Name == null ||
                 this.Name?.Equals(other.Name) == true) &&
                (this.NumRegions == null && other.NumRegions == null ||
                 this.NumRegions?.Equals(other.NumRegions) == true) &&
                (this.WikiDataId == null && other.WikiDataId == null ||
                 this.WikiDataId?.Equals(other.WikiDataId) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CallingCode = {this.CallingCode ?? "null"}");
            toStringOutput.Add($"Code = {this.Code ?? "null"}");
            toStringOutput.Add($"CurrencyCodes = {(this.CurrencyCodes == null ? "null" : $"[{string.Join(", ", this.CurrencyCodes)} ]")}");
            toStringOutput.Add($"FlagImageUri = {this.FlagImageUri ?? "null"}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"NumRegions = {(this.NumRegions == null ? "null" : this.NumRegions.ToString())}");
            toStringOutput.Add($"WikiDataId = {this.WikiDataId ?? "null"}");
        }
    }
}