// <copyright file="ErrorCodeEnum.cs" company="APIMatic">
// GeoDBCitiesAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using APIMatic.Core.Utilities.Converters;
using GeoDBCitiesAPI.Standard;
using GeoDBCitiesAPI.Standard.Utilities;
using Newtonsoft.Json;

namespace GeoDBCitiesAPI.Standard.Models
{
    /// <summary>
    /// ErrorCodeEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ErrorCodeEnum
    {
        /// <summary>
        /// ACCESSDENIED.
        /// </summary>
        [EnumMember(Value = "ACCESS_DENIED")]
        ACCESSDENIED,

        /// <summary>
        /// ENTITYNOTFOUND.
        /// </summary>
        [EnumMember(Value = "ENTITY_NOT_FOUND")]
        ENTITYNOTFOUND,

        /// <summary>
        /// INCOMPATIBLE.
        /// </summary>
        [EnumMember(Value = "INCOMPATIBLE")]
        INCOMPATIBLE,

        /// <summary>
        /// PARAMINVALID.
        /// </summary>
        [EnumMember(Value = "PARAM_INVALID")]
        PARAMINVALID,

        /// <summary>
        /// PARAMSMUTUALLYEXCLUSIVE.
        /// </summary>
        [EnumMember(Value = "PARAMS_MUTUALLY_EXCLUSIVE")]
        PARAMSMUTUALLYEXCLUSIVE,

        /// <summary>
        /// REQUESTUNPROCESSABLE.
        /// </summary>
        [EnumMember(Value = "REQUEST_UNPROCESSABLE")]
        REQUESTUNPROCESSABLE
    }
}