// <copyright file="PopulatedPlaceTypeEnum.cs" company="APIMatic">
// GeoDBCitiesAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using APIMatic.Core.Utilities.Converters;
using GeoDBCitiesAPI.Standard;
using GeoDBCitiesAPI.Standard.Utilities;
using Newtonsoft.Json;

namespace GeoDBCitiesAPI.Standard.Models
{
    /// <summary>
    /// PopulatedPlaceTypeEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum PopulatedPlaceTypeEnum
    {
        /// <summary>
        /// ADM2.
        /// </summary>
        [EnumMember(Value = "ADM2")]
        ADM2,

        /// <summary>
        /// CITY.
        /// </summary>
        [EnumMember(Value = "CITY")]
        CITY
    }
}