// <copyright file="TimeZoneResponse.cs" company="APIMatic">
// GeoDBCitiesAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using GeoDBCitiesAPI.Standard;
using GeoDBCitiesAPI.Standard.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace GeoDBCitiesAPI.Standard.Models
{
    /// <summary>
    /// TimeZoneResponse.
    /// </summary>
    public class TimeZoneResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TimeZoneResponse"/> class.
        /// </summary>
        public TimeZoneResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TimeZoneResponse"/> class.
        /// </summary>
        /// <param name="errors">errors.</param>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="rawUtcOffsetHours">rawUtcOffsetHours.</param>
        public TimeZoneResponse(
            List<Models.Error> errors = null,
            string id = null,
            string name = null,
            int? rawUtcOffsetHours = null)
        {
            this.Errors = errors;
            this.Id = id;
            this.Name = name;
            this.RawUtcOffsetHours = rawUtcOffsetHours;
        }

        /// <summary>
        /// Gets or sets Errors.
        /// </summary>
        [JsonProperty("errors", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Error> Errors { get; set; }

        /// <summary>
        /// The time-zone id
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        /// <summary>
        /// The time-zone name
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <summary>
        /// The number of hours this time-zone is offset from UTC
        /// </summary>
        [JsonProperty("rawUtcOffsetHours", NullValueHandling = NullValueHandling.Ignore)]
        public int? RawUtcOffsetHours { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TimeZoneResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is TimeZoneResponse other &&
                (this.Errors == null && other.Errors == null ||
                 this.Errors?.Equals(other.Errors) == true) &&
                (this.Id == null && other.Id == null ||
                 this.Id?.Equals(other.Id) == true) &&
                (this.Name == null && other.Name == null ||
                 this.Name?.Equals(other.Name) == true) &&
                (this.RawUtcOffsetHours == null && other.RawUtcOffsetHours == null ||
                 this.RawUtcOffsetHours?.Equals(other.RawUtcOffsetHours) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Errors = {(this.Errors == null ? "null" : $"[{string.Join(", ", this.Errors)} ]")}");
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"RawUtcOffsetHours = {(this.RawUtcOffsetHours == null ? "null" : this.RawUtcOffsetHours.ToString())}");
        }
    }
}