// <copyright file="CustomHeaderAuthenticationManager.cs" company="APIMatic">
// GeoDBCitiesAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using GeoDBCitiesAPI.Standard.Http.Request;
using APIMatic.Core.Authentication;

namespace GeoDBCitiesAPI.Standard.Authentication
{
    /// <summary>
    /// CustomHeaderAuthenticationManager Class.
    /// </summary>
    internal class CustomHeaderAuthenticationManager : AuthManager, ICustomHeaderAuthenticationCredentials
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomHeaderAuthenticationManager"/> class.
        /// </summary>
        /// <param name="customHeaderAuthentication">CustomHeaderAuthentication.</param>
        public CustomHeaderAuthenticationManager(CustomHeaderAuthenticationModel customHeaderAuthenticationModel)
        {
            XRapidapiKey = customHeaderAuthenticationModel?.XRapidapiKey;
            Parameters(paramBuilder => paramBuilder
                .Header(header => header.Setup("x-rapidapi-key", XRapidapiKey).Required())
            );
        }

        /// <summary>
        /// Gets string value for xRapidapiKey.
        /// </summary>
        public string XRapidapiKey { get; }

        /// <summary>
        /// Check if credentials match.
        /// </summary>
        /// <param name="xRapidapiKey"> The string value for credentials.</param>
        /// <returns> True if credentials matched.</returns>
        public bool Equals(string xRapidapiKey)
        {
            return xRapidapiKey.Equals(this.XRapidapiKey);
        }
    }

    public sealed class CustomHeaderAuthenticationModel
    {
        internal CustomHeaderAuthenticationModel()
        {
        }

        internal string XRapidapiKey { get; set; }

        /// <summary>
        /// Creates an object of the CustomHeaderAuthenticationModel using the values provided for the builder.
        /// </summary>
        /// <returns>Builder.</returns>
        public Builder ToBuilder()
        {
            return new Builder(XRapidapiKey);
        }

        /// <summary>
        /// Builder class for CustomHeaderAuthenticationModel.
        /// </summary>
        public class Builder
        {
            private string xRapidapiKey;

            public Builder(string xRapidapiKey)
            {
                this.xRapidapiKey = xRapidapiKey ?? throw new ArgumentNullException(nameof(xRapidapiKey));
            }

            /// <summary>
            /// Sets XRapidapiKey.
            /// </summary>
            /// <param name="xRapidapiKey">XRapidapiKey.</param>
            /// <returns>Builder.</returns>
            public Builder XRapidapiKey(string xRapidapiKey)
            {
                this.xRapidapiKey = xRapidapiKey ?? throw new ArgumentNullException(nameof(xRapidapiKey));
                return this;
            }

            /// <summary>
            /// Creates an object of the CustomHeaderAuthenticationModel using the values provided for the builder.
            /// </summary>
            /// <returns>CustomHeaderAuthenticationModel.</returns>
            public CustomHeaderAuthenticationModel Build()
            {
                return new CustomHeaderAuthenticationModel()
                {
                    XRapidapiKey = this.xRapidapiKey
                };
            }
        }
    }
    
}