// <copyright file="ICustomHeaderAuthenticationCredentials.cs" company="APIMatic">
// GeoDBCitiesAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;

namespace GeoDBCitiesAPI.Standard.Authentication
{
    /// <summary>
    /// Authentication configuration interface for CustomHeaderAuthentication.
    /// </summary>
    public interface ICustomHeaderAuthenticationCredentials
    {
        /// <summary>
        /// Gets string value for xRapidapiKey.
        /// </summary>
        string XRapidapiKey { get; }

        /// <summary>
        ///  Returns true if credentials matched.
        /// </summary>
        /// <param name="xRapidapiKey"> The string value for credentials.</param>
        /// <returns>True if credentials matched.</returns>
        bool Equals(string xRapidapiKey);
    }
}