// <copyright file="UnixDateTimeConverter.cs" company="APIMatic">
// GeoDBCitiesAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Date;

namespace GeoDBCitiesAPI.Standard.Utilities
{
    /// <summary>
    /// Extends from DateTimeConverterBase, uses unix DateTime format.
    /// </summary>
    public class UnixDateTimeConverter : CoreUnixDateTimeConverter { }
}